import { Agent, Property, Post } from './types';

export const mockAgents: Agent[] = [
  {
    id: 'agent-1',
    full_name: 'Adebayo Okafor',
    avatar_url: 'https://picsum.photos/seed/agent1/200/200',
    phone: '+2348012345678',
    whatsapp: '2348012345678',
    role: 'agent',
    bio: 'Experienced real estate agent with over 10 years in Lagos property market.',
    agency_name: 'Petrex Estate and Property Managers',
    listings_count: 12,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'agent-2',
    full_name: 'Chidinma Eze',
    avatar_url: 'https://picsum.photos/seed/agent2/200/200',
    phone: '+2348023456789',
    whatsapp: '2348023456789',
    role: 'agent',
    bio: 'Specialist in luxury properties across Abuja and Lagos with 8 years experience.',
    agency_name: 'Petrex Estate and Property Managers',
    listings_count: 8,
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'agent-3',
    full_name: 'Emeka Nwosu',
    avatar_url: 'https://picsum.photos/seed/agent3/200/200',
    phone: '+2348034567890',
    whatsapp: '2348034567890',
    role: 'agent',
    bio: 'Commercial property expert serving Port Harcourt and surrounding areas.',
    agency_name: 'Petrex Estate and Property Managers',
    listings_count: 6,
    created_at: '2024-02-01T00:00:00Z',
  },
  {
    id: 'agent-4',
    full_name: 'Fatima Aliyu',
    avatar_url: 'https://picsum.photos/seed/agent4/200/200',
    phone: '+2348045678901',
    whatsapp: '2348045678901',
    role: 'agent',
    bio: 'Land and property consultant based in Abuja FCT.',
    agency_name: 'Petrex Estate and Property Managers',
    listings_count: 9,
    created_at: '2024-02-15T00:00:00Z',
  },
];

export const mockProperties: Property[] = [
  {
    id: 'prop-1',
    title: 'Spacious Family Villa',
    slug: 'spacious-family-villa',
    description:
      'A beautiful 5-bedroom family villa with modern amenities in a serene environment. This stunning property features a large living room, modern kitchen, spacious bedrooms, and a beautiful garden. Located in the prestigious Lekki Phase 1, this villa offers the perfect blend of luxury and comfort.',
    price: 150000000,
    currency: 'NGN',
    status: 'for_sale',
    type: 'mansion',
    bedrooms: 5,
    bathrooms: 4,
    size_sqm: 450,
    address: 'Lekki Phase 1',
    city: 'Lagos',
    state: 'Lagos',
    latitude: 6.4281,
    longitude: 3.4219,
    amenities: ['Parking', 'Security', 'Swimming Pool', 'Gym', 'Generator', 'Water', 'Air Conditioning', 'Internet'],
    agent_id: 'agent-1',
    agent: mockAgents[0],
    approved: true,
    featured: true,
    views: 245,
    images: [
      { id: 'img-1-1', property_id: 'prop-1', url: 'https://picsum.photos/seed/villa1/800/600', is_primary: true, display_order: 0, created_at: '2024-01-01T00:00:00Z' },
      { id: 'img-1-2', property_id: 'prop-1', url: 'https://picsum.photos/seed/villa2/800/600', is_primary: false, display_order: 1, created_at: '2024-01-01T00:00:00Z' },
      { id: 'img-1-3', property_id: 'prop-1', url: 'https://picsum.photos/seed/villa3/800/600', is_primary: false, display_order: 2, created_at: '2024-01-01T00:00:00Z' },
    ],
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'prop-2',
    title: 'Modern Apartment Lekki',
    slug: 'modern-apartment-lekki',
    description:
      'Luxury 3-bedroom apartment with ocean views in Lekki, Lagos. Features open-plan living areas, premium finishes, and breathtaking views of the Lagos lagoon. The apartment complex includes 24/7 security, a rooftop pool, and a fully equipped gym.',
    price: 352000000,
    currency: 'NGN',
    status: 'for_sale',
    type: 'apartment',
    bedrooms: 3,
    bathrooms: 3,
    size_sqm: 180,
    address: 'Lekki Expressway',
    city: 'Lagos',
    state: 'Lagos',
    latitude: 6.4698,
    longitude: 3.5852,
    amenities: ['Parking', 'Security', 'Swimming Pool', 'Gym', 'Generator', 'Air Conditioning', 'Internet'],
    agent_id: 'agent-2',
    agent: mockAgents[1],
    approved: true,
    featured: true,
    views: 312,
    images: [
      { id: 'img-2-1', property_id: 'prop-2', url: 'https://picsum.photos/seed/apt1/800/600', is_primary: true, display_order: 0, created_at: '2024-01-15T00:00:00Z' },
      { id: 'img-2-2', property_id: 'prop-2', url: 'https://picsum.photos/seed/apt2/800/600', is_primary: false, display_order: 1, created_at: '2024-01-15T00:00:00Z' },
    ],
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'prop-3',
    title: 'Commercial Office VI',
    slug: 'commercial-office-vi',
    description:
      'Premium office space in the heart of Victoria Island. This commercial property is ideal for corporate headquarters, featuring open-plan floors, conference rooms, a reception area, and state-of-the-art facilities.',
    price: 350000000,
    currency: 'NGN',
    status: 'for_sale',
    type: 'commercial',
    bedrooms: 0,
    bathrooms: 2,
    size_sqm: 320,
    address: 'Victoria Island',
    city: 'Lagos',
    state: 'Lagos',
    latitude: 6.4281,
    longitude: 3.4219,
    amenities: ['Parking', 'Security', 'Generator', 'Air Conditioning', 'Internet'],
    agent_id: 'agent-1',
    agent: mockAgents[0],
    approved: true,
    featured: false,
    views: 178,
    images: [
      { id: 'img-3-1', property_id: 'prop-3', url: 'https://picsum.photos/seed/office1/800/600', is_primary: true, display_order: 0, created_at: '2024-01-20T00:00:00Z' },
    ],
    created_at: '2024-01-20T00:00:00Z',
    updated_at: '2024-01-20T00:00:00Z',
  },
  {
    id: 'prop-4',
    title: 'Duplex in Abuja Gwarinpa',
    slug: 'duplex-abuja-gwarinpa',
    description:
      '4-bedroom duplex in a quiet estate with 24/7 security. Perfect family home in a serene environment with excellent road infrastructure and proximity to top schools and shopping centers.',
    price: 85000000,
    currency: 'NGN',
    status: 'for_rent',
    type: 'duplex',
    bedrooms: 4,
    bathrooms: 3,
    size_sqm: 280,
    address: 'Gwarinpa Estate',
    city: 'Abuja',
    state: 'FCT',
    latitude: 9.0579,
    longitude: 7.4951,
    amenities: ['Parking', 'Security', 'Generator', 'Water', 'Internet'],
    agent_id: 'agent-4',
    agent: mockAgents[3],
    approved: true,
    featured: true,
    views: 201,
    images: [
      { id: 'img-4-1', property_id: 'prop-4', url: 'https://picsum.photos/seed/duplex1/800/600', is_primary: true, display_order: 0, created_at: '2024-02-01T00:00:00Z' },
      { id: 'img-4-2', property_id: 'prop-4', url: 'https://picsum.photos/seed/duplex2/800/600', is_primary: false, display_order: 1, created_at: '2024-02-01T00:00:00Z' },
    ],
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-02-01T00:00:00Z',
  },
  {
    id: 'prop-5',
    title: 'Land in Epe Lagos',
    slug: 'land-epe-lagos',
    description:
      'Dry land with C of O in a fast-developing area of Epe. This prime plot is perfect for residential or commercial development, located in a fast-growing area with excellent road access.',
    price: 23000000,
    currency: 'NGN',
    status: 'for_sale',
    type: 'land',
    bedrooms: 0,
    bathrooms: 0,
    size_sqm: 600,
    address: 'Epe Town',
    city: 'Lagos',
    state: 'Lagos',
    latitude: 6.5833,
    longitude: 3.9833,
    amenities: ['Security'],
    agent_id: 'agent-1',
    agent: mockAgents[0],
    approved: true,
    featured: false,
    views: 89,
    images: [
      { id: 'img-5-1', property_id: 'prop-5', url: 'https://picsum.photos/seed/land1/800/600', is_primary: true, display_order: 0, created_at: '2024-02-10T00:00:00Z' },
    ],
    created_at: '2024-02-10T00:00:00Z',
    updated_at: '2024-02-10T00:00:00Z',
  },
  {
    id: 'prop-6',
    title: 'Executive Bungalow Ikeja',
    slug: 'executive-bungalow-ikeja',
    description:
      'Well-finished 3-bedroom bungalow in a serene neighborhood in Ikeja, Lagos. Features modern kitchen, tiled floors throughout, fitted wardrobes, and a spacious backyard.',
    price: 45000000,
    currency: 'NGN',
    status: 'for_sale',
    type: 'bungalow',
    bedrooms: 3,
    bathrooms: 2,
    size_sqm: 200,
    address: 'GRA Phase 2',
    city: 'Lagos',
    state: 'Lagos',
    latitude: 6.6018,
    longitude: 3.3515,
    amenities: ['Parking', 'Security', 'Generator', 'Water'],
    agent_id: 'agent-2',
    agent: mockAgents[1],
    approved: true,
    featured: false,
    views: 134,
    images: [
      { id: 'img-6-1', property_id: 'prop-6', url: 'https://picsum.photos/seed/bungalow1/800/600', is_primary: true, display_order: 0, created_at: '2024-02-15T00:00:00Z' },
    ],
    created_at: '2024-02-15T00:00:00Z',
    updated_at: '2024-02-15T00:00:00Z',
  },
  {
    id: 'prop-7',
    title: 'Luxury Penthouse Ikoyi',
    slug: 'luxury-penthouse-ikoyi',
    description:
      'Stunning 4-bedroom penthouse apartment in the prestigious Ikoyi area. This ultra-luxury property offers panoramic views of Lagos Island, premium finishes, private pool, and concierge services.',
    price: 650000000,
    currency: 'NGN',
    status: 'for_sale',
    type: 'apartment',
    bedrooms: 4,
    bathrooms: 4,
    size_sqm: 380,
    address: 'Bourdillon Road, Ikoyi',
    city: 'Lagos',
    state: 'Lagos',
    latitude: 6.4533,
    longitude: 3.4326,
    amenities: ['Parking', 'Security', 'Swimming Pool', 'Gym', 'Generator', 'Water', 'Air Conditioning', 'Internet'],
    agent_id: 'agent-2',
    agent: mockAgents[1],
    approved: true,
    featured: true,
    views: 421,
    images: [
      { id: 'img-7-1', property_id: 'prop-7', url: 'https://picsum.photos/seed/penthouse1/800/600', is_primary: true, display_order: 0, created_at: '2024-03-01T00:00:00Z' },
      { id: 'img-7-2', property_id: 'prop-7', url: 'https://picsum.photos/seed/penthouse2/800/600', is_primary: false, display_order: 1, created_at: '2024-03-01T00:00:00Z' },
    ],
    created_at: '2024-03-01T00:00:00Z',
    updated_at: '2024-03-01T00:00:00Z',
  },
  {
    id: 'prop-8',
    title: 'Mini Flat Surulere',
    slug: 'mini-flat-surulere',
    description:
      'Clean and well-maintained mini flat in the heart of Surulere, Lagos. Features a spacious living room, bedroom, kitchen and bathroom. Great for young professionals.',
    price: 800000,
    currency: 'NGN',
    status: 'for_rent',
    type: 'apartment',
    bedrooms: 1,
    bathrooms: 1,
    size_sqm: 55,
    address: 'Bode Thomas Street',
    city: 'Lagos',
    state: 'Lagos',
    latitude: 6.5059,
    longitude: 3.3553,
    amenities: ['Security', 'Water'],
    agent_id: 'agent-3',
    agent: mockAgents[2],
    approved: true,
    featured: false,
    views: 67,
    images: [
      { id: 'img-8-1', property_id: 'prop-8', url: 'https://picsum.photos/seed/miniflat1/800/600', is_primary: true, display_order: 0, created_at: '2024-03-05T00:00:00Z' },
    ],
    created_at: '2024-03-05T00:00:00Z',
    updated_at: '2024-03-05T00:00:00Z',
  },
];

export const mockPosts: Post[] = [
  {
    id: 'post-1',
    title: 'How to Buy Your First Home in Lagos: A Complete Guide',
    slug: 'how-to-buy-first-home-lagos',
    content: `<p>Buying your first home in Lagos can be a daunting process, but with the right guidance, it can be a smooth and rewarding experience.</p>
    <h2>1. Understand the Lagos Property Market</h2>
    <p>Lagos is Nigeria's commercial capital and has one of the most dynamic property markets in Africa. Prices vary significantly by location.</p>
    <h2>2. Get Your Finances in Order</h2>
    <p>Before you start house hunting, it's essential to have your finances sorted. Consider mortgage options from Nigerian banks.</p>
    <h2>3. Choose the Right Location</h2>
    <p>Lagos is divided into the mainland and island. The island (Lekki, Victoria Island, Ikoyi) commands premium prices.</p>`,
    excerpt:
      'Buying your first home in Lagos? This comprehensive guide covers everything from financing to choosing the right neighborhood.',
    cover_image: 'https://picsum.photos/seed/blog1/800/400',
    author_id: 'agent-1',
    author: mockAgents[0],
    published: true,
    category: 'Buying Guide',
    created_at: '2024-03-01T00:00:00Z',
  },
  {
    id: 'post-2',
    title: 'Top 5 Emerging Real Estate Hotspots in Abuja 2024',
    slug: 'top-5-emerging-real-estate-hotspots-abuja-2024',
    content: `<p>Abuja's real estate market continues to grow, with several emerging areas offering excellent investment opportunities.</p>
    <h2>1. Gwarinpa</h2>
    <p>Gwarinpa is one of the largest residential estates in West Africa and continues to attract significant investment.</p>
    <h2>2. Katampe</h2>
    <p>With its elevated terrain offering scenic views of the city, Katampe Extension is becoming increasingly popular.</p>`,
    excerpt: 'Discover the most promising real estate investment areas in Abuja for 2024 and beyond.',
    cover_image: 'https://picsum.photos/seed/blog2/800/400',
    author_id: 'agent-4',
    author: mockAgents[3],
    published: true,
    category: 'Market Updates',
    created_at: '2024-03-10T00:00:00Z',
  },
  {
    id: 'post-3',
    title: 'Renting vs Buying in Nigeria: Which is Right for You?',
    slug: 'renting-vs-buying-nigeria',
    content: `<p>One of the biggest financial decisions you'll make is whether to rent or buy property. Here's what you need to consider in the Nigerian context.</p>
    <h2>The Case for Renting</h2>
    <p>Renting offers flexibility, lower upfront costs, and freedom from maintenance responsibilities.</p>
    <h2>The Case for Buying</h2>
    <p>Buying property in Nigeria is considered one of the best long-term investments due to consistent price appreciation.</p>`,
    excerpt:
      "Making the rent vs buy decision? We break down the pros and cons for Nigerian property seekers.",
    cover_image: 'https://picsum.photos/seed/blog3/800/400',
    author_id: 'agent-2',
    author: mockAgents[1],
    published: true,
    category: 'Renting Guide',
    created_at: '2024-03-15T00:00:00Z',
  },
  {
    id: 'post-4',
    title: 'Understanding Land Titles in Nigeria: C of O, R of O and More',
    slug: 'understanding-land-titles-nigeria',
    content: `<p>Land documentation is one of the most critical aspects of property ownership in Nigeria. Here's what you need to know.</p>
    <h2>Certificate of Occupancy (C of O)</h2>
    <p>The C of O is the most secure form of land title in Nigeria, issued by state governments.</p>`,
    excerpt:
      "Navigate Nigeria's complex land title system with our comprehensive guide to C of O, R of O, and other title documents.",
    cover_image: 'https://picsum.photos/seed/blog4/800/400',
    author_id: 'agent-1',
    author: mockAgents[0],
    published: true,
    category: 'Legal Guide',
    created_at: '2024-03-20T00:00:00Z',
  },
];
